;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsList]
GameplayTagList=(Tag="GameplayAttribute.Heat.Decay.Block",DevComment="")
GameplayTagList=(Tag="GameplayAttribute.Energy.Regeneration.Block",DevComment="")
